name: Hello World2


on: [push]
jobs:

  build:
   
    runs-on: ubuntu-latestgit

    steps:    
     - uses: actions/checkout@v2    
     - name: Run pwd      
       run: pwd    
     - name: Run ls -al      
       run: ls -al 
